#!/usr/bin/env perl
use strict;
use warnings;
use Fatal qw(open close);

my $emcc = "../emscripten/emcc";

my($c_file, $output_dir) = @ARGV;
($c_file && $output_dir) or die "usage: emcc-jsx c_file output_dir\n";

my $output = `$emcc -s LINKABLE=1 -o $output_dir/$c_file.js $c_file 2>&1`;

my $class_name = 'EMS';

open my($out), ">", "$output_dir/$c_file.jsx";

printf $out <<'HEAD', $class_name, $c_file, $output_dir;
// emscripten JS API
native class _C {
  static function ccall(name : string, returnType : string, argsType : string[], args : variant) : variant;
} = "require('./%3$s/%2$s.js')";

// from C file
class %1$s {
HEAD

print $out $output;

printf $out <<'FOOT', $class_name;
} // %1$s

// vim: set tabstop=2 shiftwidth=2 expandtab:
FOOT

close $out;

# vim: set tabstop=2 shiftwidth=2 expandtab:
